Repository dnd-side-project/dnd-10th-6-backend, pull requests merged in 2024-03, with the labels that each got.

#101 대시보드 Character 타입에 questionId 포함
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardService.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/CharacterDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/DashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
Labels: ✨ FEAT

#103 SurveyAnswer 제거 및 Survey와 통합
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/entity/Dashboard.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/AverageStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Statistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Statistics.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyAnswerService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswer.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Answer.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
  src/test/java/com/dnd/namuiwiki/domain/survey/SurveyAnswerServiceTest.java
  src/test/java/com/dnd/namuiwiki/domain/survey/SurveyServiceTest.java
  src/test/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswerTest.java
Labels: 🌈 REFACTOR

#108 모니터링을 위해 actuator, micrometer 추가
  build.gradle
Labels: ✨ FEAT

#111 내가 작성한 설문 목록 오류 수정
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SentSurveyDto.java
Labels: 🐛 BUG

#112 직접입력일 경우에도 counting 하도록 수정(#105)
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java
Labels: 🐛 BUG

#118 fix: 직접 입력일 경우 option 카운팅하지 않도록 수정
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java
Labels: 🐛 BUG

#124 feat: 설문 단일 조회 시 questionName 필드 추가(#122)
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
Labels: ✨ FEAT

#130 질문별 상세보기 questionName 필드 추가(#129)
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetAnswersByQuestionResponse.java
Labels: ✨ FEAT

#131 feat: 대시보드 조회 시 직접입력 옵션 퍼센트 응답에 포함(#128)
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/RatioDto.java
Labels: ✨ FEAT

#134 설문 조회 응답에 optionName 필드 추가(#133)
  src/main/java/com/dnd/namuiwiki/domain/option/entity/Option.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
Labels: ✨ FEAT

#137 feat: 질문이 NUMERIC 타입일 경우, 답변을 정수로 응답(#136)
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
Labels: ✨ FEAT

#140 fix: 0일 경우 나누기 예외처리(#136)
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
Labels: 🐛 BUG

#142 Question Repository 메소드 캐싱(#98)
  src/main/java/com/dnd/namuiwiki/config/CacheConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionRepository.java
  src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java
Labels: 🌈 REFACTOR

#143 통계 업데이트를 이벤트 기반으로 변경(#92)
  src/main/java/com/dnd/namuiwiki/common/exception/AsyncExceptionHandler.java
  src/main/java/com/dnd/namuiwiki/config/AsyncConfiguration.java
  src/main/java/com/dnd/namuiwiki/config/EventConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyEventHandler.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SurveyCreatedEvent.java
Labels: 🌈 REFACTOR

#145 내가 받은 설문 단일 조회에 owner 검증 로직 추가(#144)
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
Labels: ✨ FEAT
