Repository dnd-side-project/dnd-10th-6-backend, pull requests merged in 2024-02, with the labels that each got.

#3 RuntimeException Handler 구축
  build.gradle
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorException.java
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/common/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/namuiwiki/common/exception/dto/ErrorResponseDto.java
  src/main/java/com/dnd/namuiwiki/config/.gitkeep
  src/main/java/com/dnd/namuiwiki/domain/entity/.gitkeep
  src/main/java/com/dnd/namuiwiki/domain/repository/.gitkeep
  src/main/java/com/dnd/namuiwiki/insfrastructure/config/.gitkeep
  src/main/java/com/dnd/namuiwiki/insfrastructure/persistence/.gitkeep
Labels: ✨ FEAT

#8 feat: WebMvcConfiguration에 cors 관련 설정 추가(#7)
  src/main/java/com/dnd/namuiwiki/config/.gitkeep
  src/main/java/com/dnd/namuiwiki/config/WebConfiguration.java
Labels: ✨ FEAT

#4 카카오 OAuth 로그인 회원 인증 로직 구현
  .gitignore
  src/main/java/com/dnd/namuiwiki/application/oauth/OAuthProviderService.java
  src/main/java/com/dnd/namuiwiki/application/oauth/OAuthService.java
  src/main/java/com/dnd/namuiwiki/application/oauth/dto/OAuthUserInfoDto.java
  src/main/java/com/dnd/namuiwiki/application/oauth/kakao/OAuthKakaoService.java
  src/main/java/com/dnd/namuiwiki/application/oauth/kakao/dto/KakaoOAuthTokenRequest.java
  src/main/java/com/dnd/namuiwiki/application/oauth/kakao/dto/KakaoOAuthTokenResponse.java
  src/main/java/com/dnd/namuiwiki/application/oauth/kakao/dto/KakaoOAuthUserInfoRequest.java
  src/main/java/com/dnd/namuiwiki/application/oauth/kakao/dto/KakaoOAuthUserInfoResponse.java
  src/main/java/com/dnd/namuiwiki/application/oauth/type/OAuthProvider.java
  src/main/java/com/dnd/namuiwiki/common/annotation/Enum.java
  src/main/java/com/dnd/namuiwiki/common/validator/EnumValidator.java
  src/main/java/com/dnd/namuiwiki/insfrastructure/config/.gitkeep
  src/main/java/com/dnd/namuiwiki/presentation/auth/AuthController.java
  src/main/java/com/dnd/namuiwiki/presentation/auth/dto/OAuthLoginRequest.java
  src/main/java/com/dnd/namuiwiki/presentation/auth/dto/OAuthLoginResponse.java
  src/main/java/com/dnd/namuiwiki/presentation/dto/ResponseDto.java
Labels: ✨ FEAT

#6 JWT 토큰 인증 구현(refresh 진행중)
  build.gradle
  src/main/java/com/dnd/namuiwiki/jwt/JwtFilter.java
  src/main/java/com/dnd/namuiwiki/jwt/JwtProvider.java
  src/main/java/com/dnd/namuiwiki/jwt/JwtService.java
  src/main/java/com/dnd/namuiwiki/jwt/TokenUserInfoDto.java
  src/main/java/com/dnd/namuiwiki/presentation/auth/AuthController.java
  src/main/java/com/dnd/namuiwiki/presentation/auth/dto/OAuthLoginResponse.java
  src/main/java/com/dnd/namuiwiki/user/User.java
  src/main/java/com/dnd/namuiwiki/user/UserRepository.java
  src/main/java/com/dnd/namuiwiki/user/UserService.java
  src/test/java/com/dnd/namuiwiki/jwt/JwtProviderTest.java
Labels: ✨ FEAT

#16 spring docs openapi 스웨거 설정
  build.gradle
Labels: ✨ FEAT

#14 문항 조회 API 구현
  build.gradle
  src/main/java/com/dnd/namuiwiki/domain/option/OptionRepository.java
  src/main/java/com/dnd/namuiwiki/domain/option/dto/OptionDto.java
  src/main/java/com/dnd/namuiwiki/domain/option/entity/Option.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionController.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionRepository.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionJsonDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
  src/main/java/com/dnd/namuiwiki/domain/question/type/QuestionType.java
  src/main/resources/json/base-document.json
Labels: ✨ FEAT

#19 Jwt 추가 구현(#13)
  src/main/java/com/dnd/namuiwiki/common/dto/ResponseDto.java
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/common/filter/JwtExceptionHandlerFilter.java
  src/main/java/com/dnd/namuiwiki/common/filter/JwtFilter.java
  src/main/java/com/dnd/namuiwiki/config/FilterConfiguration.java
  src/main/java/com/dnd/namuiwiki/config/WebConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/auth/AuthController.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/RefreshResponse.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtAuthorization.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtAuthorizationArgumentResolver.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtProvider.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtService.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/kakao/dto/KakaoOAuthUserInfoResponse.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserRepository.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
  src/test/java/com/dnd/namuiwiki/jwt/JwtProviderTest.java
Labels: ✨ FEAT

#20 OAuth, Jwt 구현 배포
  .gitignore
  build.gradle
  src/main/java/com/dnd/namuiwiki/common/annotation/Enum.java
  src/main/java/com/dnd/namuiwiki/common/dto/ResponseDto.java
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorException.java
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/common/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/namuiwiki/common/exception/dto/ErrorResponseDto.java
  src/main/java/com/dnd/namuiwiki/common/filter/JwtExceptionHandlerFilter.java
  src/main/java/com/dnd/namuiwiki/common/filter/JwtFilter.java
  src/main/java/com/dnd/namuiwiki/common/validator/EnumValidator.java
  src/main/java/com/dnd/namuiwiki/config/FilterConfiguration.java
  src/main/java/com/dnd/namuiwiki/config/WebConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/auth/AuthController.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/OAuthLoginRequest.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/OAuthLoginResponse.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/RefreshResponse.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtAuthorization.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtAuthorizationArgumentResolver.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtProvider.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtService.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/dto/TokenUserInfoDto.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/OAuthProviderService.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/OAuthService.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/dto/OAuthUserInfoDto.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/kakao/OAuthKakaoService.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/kakao/dto/KakaoOAuthTokenRequest.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/kakao/dto/KakaoOAuthTokenResponse.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/kakao/dto/KakaoOAuthUserInfoRequest.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/kakao/dto/KakaoOAuthUserInfoResponse.java
  src/main/java/com/dnd/namuiwiki/domain/oauth/type/OAuthProvider.java
  src/main/java/com/dnd/namuiwiki/domain/option/OptionRepository.java
  src/main/java/com/dnd/namuiwiki/domain/option/dto/OptionDto.java
  src/main/java/com/dnd/namuiwiki/domain/option/entity/Option.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionController.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionRepository.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionJsonDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
  src/main/java/com/dnd/namuiwiki/domain/question/type/QuestionType.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserRepository.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
  src/main/resources/json/base-document.json
  src/test/java/com/dnd/namuiwiki/jwt/JwtProviderTest.java
Labels: ✨ FEAT

#22 infra: configmap으로 application.yaml 주입
  k8s/configmap.yaml
  k8s/deployment.yaml
Labels: ✨ FEAT

#25 bug: User 생성자 수정(#24)
  src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
Labels: 🐛 BUG

#27 Bug/#24
  src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
Labels: 🐛 BUG

#18 설문 생성 API
  build.gradle
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/domain/auth/AuthController.java
  src/main/java/com/dnd/namuiwiki/domain/jwt/JwtProvider.java
  src/main/java/com/dnd/namuiwiki/domain/option/OptionRepository.java
  src/main/java/com/dnd/namuiwiki/domain/option/dto/OptionDto.java
  src/main/java/com/dnd/namuiwiki/domain/option/entity/Option.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionJsonDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/type/QuestionType.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyAnswerService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswer.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/AnswerDto.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/CreateSurveyRequest.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/CreateSurveyResponse.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java
  src/main/java/com/dnd/namuiwiki/domain/survey/type/AnswerType.java
  src/main/java/com/dnd/namuiwiki/domain/survey/type/Period.java
  src/main/java/com/dnd/namuiwiki/domain/survey/type/Relation.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
  src/main/resources/json/base-document.json
  src/test/java/com/dnd/namuiwiki/domain/question/dto/QuestionTypeTest.java
  src/test/java/com/dnd/namuiwiki/domain/survey/SurveyAnswerServiceTest.java
  src/test/java/com/dnd/namuiwiki/domain/survey/SurveyServiceTest.java
  src/test/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswerTest.java
Labels: ✨ FEAT

#31 설문 생성 시 통계 업데이트
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardRepository.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/type/DashboardType.java
  src/main/java/com/dnd/namuiwiki/domain/option/dto/OptionDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
  src/main/java/com/dnd/namuiwiki/domain/question/type/QuestionName.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/AverageStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Legend.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Statistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Statistics.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/entity/Dashboard.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/type/StatisticsType.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyAnswerService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswer.java
  src/main/resources/json/base-document.json
  src/test/java/com/dnd/namuiwiki/domain/survey/SurveyAnswerServiceTest.java
  src/test/java/com/dnd/namuiwiki/domain/survey/SurveyServiceTest.java
Labels: ✨ FEAT

#36 대시 보드 조회 API
  src/main/java/com/dnd/namuiwiki/common/converter/EnumConverterFactory.java
  src/main/java/com/dnd/namuiwiki/config/WebConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardController.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardRepository.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardService.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/CharacterDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/DashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/DashboardDto.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/GetDashboardRequest.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/RatioDto.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/entity/Dashboard.java
  src/main/java/com/dnd/namuiwiki/domain/option/OptionRepository.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Legend.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/RatioStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Statistics.java
  src/main/resources/json/base-document.json
Labels: ✨ FEAT

#42 fix: getFirst를 get 메소드로 변경(#41)
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
Labels: ✨ FEAT

#46 사용자 프로필 조회 및 수정 api 구현
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserController.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
  src/main/java/com/dnd/namuiwiki/domain/user/dto/EditUserProfileRequest.java
  src/main/java/com/dnd/namuiwiki/domain/user/dto/UserProfileDto.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
Labels: ✨ FEAT

#51 유저 퍼블릭 정보 조회 api 구현
  src/main/java/com/dnd/namuiwiki/domain/user/UserController.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserService.java
  src/main/java/com/dnd/namuiwiki/domain/user/dto/GetUserPublicProfileResponse.java
Labels: ✨ FEAT

#62 MOULTI_CHOICE에 옵션에 MANUAL 옵션 추가(#56)
  src/main/resources/json/base-document.json
Labels: ✨ FEAT

#61 모든 Entity에 createdAt, updatedAt 필드 추가(#33)
  src/main/java/com/dnd/namuiwiki/common/model/BaseTimeEntity.java
  src/main/java/com/dnd/namuiwiki/config/MongoConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/entity/Dashboard.java
  src/main/java/com/dnd/namuiwiki/domain/option/entity/Option.java
  src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java
  src/main/java/com/dnd/namuiwiki/domain/user/entity/User.java
Labels: ✨ FEAT

#55 JwtExceptionHandlerFilter에서 CORS 설정(#54)
  .github/workflows/ci.yml
  src/main/java/com/dnd/namuiwiki/common/filter/JwtExceptionHandlerFilter.java
  src/main/java/com/dnd/namuiwiki/config/FilterConfiguration.java
Labels: 🐛 BUG

#65 설문별 상세보기 API 구현
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/common/model/BaseTimeEntity.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/entity/Survey.java
  src/main/resources/application.properties
Labels: ✨ FEAT

#53 질문별 상세보기 API(#48)
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/domain/survey/AnswerController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetAnswersByQuestionResponse.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
  src/main/java/com/dnd/namuiwiki/domain/survey/type/Period.java
  src/main/java/com/dnd/namuiwiki/domain/survey/type/Relation.java
  src/test/java/com/dnd/namuiwiki/domain/survey/SurveyServiceTest.java
Labels: ✨ FEAT

#67 feat: 문항 조회 시 타입 필터 추가(#66)
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionController.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
Labels: ✨ FEAT

#68 Question에 reasonRequired 필드 추가
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionService.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java
  src/main/java/com/dnd/namuiwiki/domain/question/entity/Question.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswer.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/AnswerDto.java
  src/main/resources/json/base-document.json
Labels: ✨ FEAT

#71 feat: 내가 받은 설문 조회 API (#70)
  src/main/java/com/dnd/namuiwiki/common/dto/PageableDto.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/ReceivedSurveyDto.java
Labels: ✨ FEAT

#72 feat: permitted url을 method도 함께 검증(#47)
  src/main/java/com/dnd/namuiwiki/common/filter/JwtFilter.java
  src/main/java/com/dnd/namuiwiki/config/FilterConfiguration.java
Labels: ✨ FEAT

#77 질문별 상세보기 응답에 작성일자 포함
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SingleAnswerWithSurveyDetailDto.java
Labels: 🐛 BUG

#45 전체 통계량 필요한 대시보드 계산 기능 추가(#38)
  src/main/java/com/dnd/namuiwiki/common/util/ArithmeticUtils.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardService.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/entity/Dashboard.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsRepository.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/AverageStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/BorrowingLimitEntireStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/EntireStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/Statistic.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/model/entity/PopulationStatistic.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
Labels: ✨ FEAT

#79 내가 작성한 설문 목록 조회 API
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyRepository.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/CreateSurveyRequest.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/SentSurveyDto.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserController.java
Labels: ✨ FEAT

#80 feat: 빌릴 수 있는 액수 범위 설정(#75)
  src/main/java/com/dnd/namuiwiki/common/exception/ApplicationErrorType.java
  src/main/java/com/dnd/namuiwiki/domain/question/type/QuestionName.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/SurveyAnswer.java
Labels: ✨ FEAT

#82 feat: 설문별 상세보기 API 구현(#49)
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyService.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
Labels: 🐛 BUG

#85 설문 상세보기 응답에 text, value 추가
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
Labels: ✨ FEAT

#86 fix: 설문 상세 조회 응답에 option value 포함(#83)
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
Labels: ✨ FEAT

#84 스웨거 설명 추가
  src/main/java/com/dnd/namuiwiki/common/annotation/DisableSwaggerSecurity.java
  src/main/java/com/dnd/namuiwiki/config/SwaggerConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/auth/AuthController.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/OAuthLoginRequest.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/OAuthLoginResponse.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/RefreshResponse.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/SignUpRequest.java
  src/main/java/com/dnd/namuiwiki/domain/auth/dto/SignUpResponse.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardController.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/DashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/DashboardDto.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/dto/GetDashboardRequest.java
  src/main/java/com/dnd/namuiwiki/domain/question/QuestionController.java
  src/main/java/com/dnd/namuiwiki/domain/question/dto/QuestionDto.java
  src/main/java/com/dnd/namuiwiki/domain/survey/AnswerController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/SurveyController.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/AnswerDto.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/CreateSurveyRequest.java
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/CreateSurveyResponse.java
  src/main/java/com/dnd/namuiwiki/domain/user/UserController.java
  src/main/java/com/dnd/namuiwiki/domain/user/dto/EditUserProfileRequest.java
  src/main/java/com/dnd/namuiwiki/domain/user/dto/GetUserPublicProfileResponse.java
  src/main/java/com/dnd/namuiwiki/domain/user/dto/UserProfileDto.java
Labels: 📄 DOCS

#91 대시보드에서 totalCount 0인 경우 percentage 0으로 처리
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
Labels: 🐛 BUG

#93 설문 작성 시 통계 작업 비동기 처리
  src/main/java/com/dnd/namuiwiki/config/AsyncConfiguration.java
  src/main/java/com/dnd/namuiwiki/domain/statistic/StatisticsService.java
Labels: ✨ FEAT

#94 feat: 대시보드 응답에 questionId 추가
  src/main/java/com/dnd/namuiwiki/domain/dashboard/DashboardService.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/BestWorthDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/CharacterDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/DashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/HappyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/MoneyDashboardComponent.java
  src/main/java/com/dnd/namuiwiki/domain/dashboard/model/SadDashboardComponent.java
Labels: ✨ FEAT

#96 Question 순서 정합성 오류 수정
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
Labels: 🐛 BUG

#97 release 0.0.7
  src/main/java/com/dnd/namuiwiki/domain/survey/model/dto/GetSurveyResponse.java
Labels: 🐛 BUG
